# This file is the parameters.yml file for CircleCI builds
parameters:
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     circle_test
    database_user:     ubuntu
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    secret:            CircleCI

    # Oauth2 credentials for the test app
    oauth_test_client_id: ~
    oauth_test_client_secret: ~
    oauth_test_redirect_uri: ~

    # Paypal
    paypal_rest_api_client_id: ~
    paypal_rest_api_secret: ~
    paypal_classic_api_username: ~
    paypal_classic_api_password: ~
    paypal_classic_api_signature: ~
